# Start with the python:3.11 base image


# set the working directory for the following commands


# copy requirements.txt file into /app


# run `pip install --no-cache-dir -r requirements.txt` to install dependecies


# copy the rest of the files from the directory


# make the directory for sqlite


# expose the port for FastAPI


# run the command to start the app

